Water-2746 Two Part Tariff integration tests
DEFRA/water-abstraction-service pull request #1245
Opened 2020-12-08 09:30 UTC by Stephan-Hough

feat/water-2746
-- 2 new scenarios added to the integration test pack
-- Two Part Tariff Summer and Winter bill runs
-- Annual Bill run fixed
-- Config changed to make the integration tests work with Bull MQ

2020-12-10 13:20 UTC, james-siteclick requested changes
CI seems to be failing

2020-12-10 13:29 UTC, Stephan-Hough commented on integration-tests/billing/services/data/return-lines.js
> +  metadata: 'metadata'
I believe the meta data is not required. I ran the tests with and without meta data and in both cases the tests passed so I decided to take it out. However, the data is there in a previous commit if this needs to be explored further.

2020-12-10 13:34 UTC, Stephan-Hough commented on config.js
> +const isTravis = process.env.TRAVIS || process.env.NODE_ENV === 'test';
Yeah I wasn't sure about this. It's something that Tim suggested I add in. When I was investigating the test failing to execute the with the introduction of BullMQ i believe it was only the lazy db connection that was causing issues.

2020-12-14 16:15 UTC, timtamimi commented on config.js
> +const isTravis = process.env.TRAVIS || process.env.NODE_ENV === 'test';
An alternative might be to use `process.env.TEST_MODE`

2021-01-11 09:05 UTC, timtamimi commented
Converted to draft pending further tests

2021-01-15 13:05 UTC, closed without merging

2021-01-15 13:06 UTC, Stephan-Hough commented
forked and closed in a different pull request https://github.com/DEFRA/water-abstraction-service/pull/1266