Feat: Store invoice numbers and totals when batch is sent
DEFRA/water-abstraction-service pull request #1262
Opened 2021-01-11 11:19 UTC by DGajewska

WATER-2976

* Adds invoice_number to water.billing_invoices
* Adds invoiceNumber to Invoice model
* Update CM decorators to use cm transaction details, if availble
* Refactors CM decorators
* Persists invoice number and totals data

2021-01-12 13:01 UTC, james-siteclick requested changes
Looks really good generally, couple of minor questions

2021-01-15 09:43 UTC, DGajewska commented on src/lib/connectors/repos/billing-invoices.js
> +const update = async (billingInvoiceId, changes) => BillingInvoice
Yes, thank you. Updated

2021-01-15 11:26 UTC, DGajewska commented on src/modules/billing/mappers/charge-module-decorators.js
> +  return mapValues(groupedByCustomer, groupTransactionsByFinancialYear);
I have simplified this based on your suggestions. Thank you

2021-01-15 13:29 UTC, DGajewska commented on src/modules/billing/mappers/charge-module-decorators.js
> +  const transactionWithInvoiceNumber = customerFinYearSummary.transactions.find(transaction => !!transaction.transactionReference);
Yes, this is a good point. I've now included this :)

2021-01-18 13:02 UTC, james-siteclick approved these changes

2021-01-19 15:22 UTC, merged