Supported Sources importer code
DEFRA/water-abstraction-service pull request #1569
Opened 2021-11-15 19:57 UTC by DashCoder

2021-11-16 13:58 UTC, Stephan-Hough commented on migrations/sqls/20211116190900-create-supported-sources-table-up.sql
> +  date_updated timestamp,
change date_updated to timestamp not null as well

2021-11-16 14:04 UTC, Stephan-Hough commented on src/modules/billing/jobs/sync-supported-sources.js
> +// Charge Categories Repo
this comment needs removed or updated

2021-11-16 14:07 UTC, Stephan-Hough requested changes
couple of minor comments

2021-11-16 16:33 UTC, Stephan-Hough approved these changes

2021-11-17 16:01 UTC, timtamimi approved these changes

2021-11-17 16:06 UTC, merged