chore: use standard js for linting
DEFRA/water-abstraction-service pull request #1696
Opened 2022-05-19 14:57 UTC by jonathangoulding

2022-06-22 08:32 UTC, Jozzey approved these changes
Looks good 👍🏼

2022-06-23 08:09 UTC, StuAA78 requested changes
Just a couple of small suggested changes to `package.json`

2022-06-23 08:09 UTC, StuAA78 commented on package.json
> +    "lint": "standard ",
There's a space after `standard` that doesn't need to be there. 

We could keep `lint:fix` as standard does support this

```suggestion
    "lint": "standard",
    "lint:fix": "standard --fix",
```

2022-06-23 10:56 UTC, StuAA78 approved these changes

2022-06-23 17:20 UTC, merged