Refactor removal of lodash code
DEFRA/water-abstraction-service pull request #2068
Opened 2023-03-21 15:12 UTC by Beckyrose200

https://github.com/DEFRA/water-abstraction-team/issues/25

In our code base, we've been gradually replacing Lodash code with vanilla JavaScript to reduce the library's usage. However, we've found a few Lodash functions that we still need to use in certain parts of the code. To better organize these functions, we created separate modules for them, which were then called throughout the code base. After creating several of these modules, we decided it would be cleaner to move all of the Lodash modules into a single file and export them from there. This pull request implements that change.

2023-03-22 09:22 UTC, Cruikshanks requested changes
It's so tidy now! 😍 

Just a quick correction in the module documentation.

2023-03-22 09:22 UTC, Cruikshanks commented on src/lib/object-helpers.js
> + */
Just a copy & paste thing to correct! 😁 

```suggestion
/**
 * Collection of helper functions that allowed us to move away from Lodash
 * @module ObjectHelpers
 */
```

2023-03-22 13:39 UTC, StuAA78 approved these changes

2023-03-23 10:24 UTC, Cruikshanks approved these changes

2023-03-23 10:35 UTC, merged