Refactor Lodash Code Changes
DEFRA/water-abstraction-service pull request #2096
Opened 2023-04-05 10:51 UTC by Beckyrose200

https://github.com/DEFRA/water-abstraction-team/issues/25

In our code base, we've been gradually replacing Lodash code with vanilla JavaScript to reduce the library's usage. This pull request is a refactor on some of the changes that have been made to remove the Lodash code.

2023-04-05 15:01 UTC, StuAA78 requested changes

2023-04-05 15:01 UTC, StuAA78 commented on src/modules/notify/connectors/scheduled-notification.js
>    }
Looking at how we're iterating in `src/modules/batch-notifications/config/returns/lib/get-recipients.js` I suspect we could write this to work the same way:
```js
  for (const [key, value] of Object.entries(snakeCaseData)) {
    dataStringify[key] = Array.isArray(value) ? JSON.stringify(value) : value
  }
```

2023-04-06 08:48 UTC, Jozzey approved these changes
<img src="https://media2.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif"/>

2023-04-06 08:50 UTC, StuAA78 approved these changes

2023-04-06 09:13 UTC, merged